# Checks the health of the workflow YML files in this monorepo.
name: checkhealth

on:
  push:

jobs:
  checkhealth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Rust files are formatted
        run: git ls-files '*.rs' | xargs rustfmt --check

      # Run our in-house health-check tooling.
      - run: cargo install --locked --force --path .
        working-directory: health
      - run: monorepo-checkhealth
