name: simple CI

on:
  push:

jobs:
  M:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.M.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: M
        run: |
          JSON=$(cat .github/workflows/os.json)
          JSON="${JSON//$'\n'/}"
          echo "matrix=${JSON}"
          echo "matrix=${JSON}" >> $GITHUB_OUTPUT

  t-runner:
    # Let this job be a demonstrator of how a matrix can be read from a
    # preceding job, loaded from a JSON file.
    needs: M
    strategy:
      matrix:
        os: ${{ fromJson(needs.M.outputs.matrix) }}
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - working-directory: code/tools/t-runner
        run: make build

  numerical-methods:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
          - windows-2025
          - windows-2022
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/numerical-methods
    steps:
      - uses: actions/checkout@v6
      - name: build
        run: cargo build --release
      - name: run tests
        run: cargo test --release

  stats-calc:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/stats-calc
    steps:
      - uses: actions/checkout@v6
      - name: build
        run: cargo build --release
      - name: run tests
        run: cargo test --release

  draw-rs:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/draw-rs
    steps:
      - uses: actions/checkout@v6
      - run: cargo build

  mirror-debian-setup-instructions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          path: x
      - uses: actions/checkout@v6
        with:
          path: y
          repository: nguyenvukhang/debian13
          token: ${{ secrets.GH_DEBIAN13_TOKEN }}
      - run: git config --global user.name 'github-actions[bot]'
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - working-directory: y
        run: |
          git ls-files | xargs rm -r
          git branch -m e2db05ee9f448b75626f40d3d9002ba1a917f0a7
          git checkout --orphan main
          cp -r ${{ github.workspace }}/x/code/docs/debian13-setup/* .
          git add --all
          git commit -m 'First try'
          git push --force --set-upstream origin main

  heliumd:
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - run: make build
        working-directory: code/tools/wacom-macos-precision-mode-daemon

  diff-rs:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - run: cargo build
        working-directory: code/tools/diff-rs
