name: git-ln build

on:
  push:
    paths:
      - "code/tools/ln/**/*"
      - .github/workflows/git-ln.build.yml
  workflow_dispatch:

jobs:
  build-c:
    strategy:
      matrix:
        os: [
            # [latest stuff]
            ubuntu-latest,
            macos-latest,
            # [fixed versions]
            ubuntu-24.04,
            ubuntu-22.04,
            macos-15,
            macos-14,
            # [unsupported]
            # windows-latest,
            # windows-2025,
            # windows-2022,
          ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/ln/c
    steps:
      - uses: actions/checkout@v6
      - run: make configure
      - run: make install
  build-zig-rust:
    strategy:
      matrix:
        os: [
            # [latest stuff]
            ubuntu-latest,
            macos-latest,
            # [fixed versions]
            ubuntu-24.04,
            ubuntu-22.04,
            macos-15,
            macos-14,
            # [unsupported]
            windows-latest,
            windows-2025,
            windows-2022,
          ]
        lang: [zig, rust]
        include:
          - lang: zig
            tool: zig
          - lang: rust
            tool: cargo
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/ln/${{ matrix.lang }}
    steps:
      - uses: actions/checkout@v6
      - run: cp build.zig.zon ${{ github.workspace }}
        if: ${{ matrix.lang == 'zig' }}
      - uses: mlugg/setup-zig@v2
        if: ${{ matrix.lang == 'zig' }}
      - run: ${{ matrix.tool }} build
