name: gitnu tests

on:
  push:
    paths:
      - "code/tools/gitnu/**/*"
      - .github/workflows/gitnu.yml
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Run tests
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cargo build
          cargo test
        working-directory: code/tools/gitnu/rust

  # publish-crates-io:
  #   name: Publish to Crates.io
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #       with:
  #         ref: v${{ needs.inc.outputs.version }}
  #
  #     - uses: katyo/publish-crates@v2
  #       with:
  #         registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
