name: gitnu-c tests

on:
  push:
    paths:
      - "code/tools/gitnu/c/**/*"
      - .github/workflows/gitnu-c.yml
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/gitnu/c
    steps:
      - uses: actions/checkout@v6
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: make setup-commands
      - run: make test
      - run: sudo make install
