name: kopiwm build

on:
  push:
    paths:
      - "code/tools/kopiwm/**/*"
      - .github/workflows/kopiwm.build.yml
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [
            # [latest stuff]
            ubuntu-latest,
            # [fixed versions]
            ubuntu-24.04,
            ubuntu-22.04,
          ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/kopiwm
    steps:
      - uses: actions/checkout@v6
      - run: cp build.zig.zon ${{ github.workspace }}
      - uses: mlugg/setup-zig@v2
      - run: |
          sudo apt update --yes
          sudo apt install --yes libx11-dev libxft-dev libfreetype-dev libfontconfig-dev
      - run: zig build
