name: simple tests

on:
  push:

jobs:
  M:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.M.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: M
        run: |
          JSON=$(cat .github/workflows/os.json)
          JSON="${JSON//$'\n'/}"
          echo "matrix=${JSON}"
          echo "matrix=${JSON}" >> $GITHUB_OUTPUT

  t-runner:
    # Let this job be a demonstrator of how a matrix can be read from a
    # preceding job, loaded from a JSON file.
    needs: M
    strategy:
      matrix:
        os: ${{ fromJson(needs.M.outputs.matrix) }}
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - working-directory: code/tools/t-runner
        run: make build

  numerical-methods:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
          - windows-2025
          - windows-2022
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/numerical-methods
    steps:
      - uses: actions/checkout@v6
      - name: build
        run: cargo build --release
      - name: run tests
        run: cargo test --release

  stats-calc:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: code/tools/stats-calc
    steps:
      - uses: actions/checkout@v6
      - name: build
        run: cargo build --release
      - name: run tests
        run: cargo test --release
